### ISSUE TITLE
CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)

### ISSUE THREAD

**Issue by boaty** [yydiao1025/Macformer#3]
hello,

I deployed macformer on ubuntu 22 and the installation part run without error but the testing_beam_search.sh is not working. I used git clone to download main folder and used zip download for downloading model and data.

i ran code in testing_beam_search.py
```

dataset_name=ChEMBL
model=${dataset_name}_a2_model_average.pt

echo $dataset_name
echo $model

python translate.py -model models/${model} \
                    -src data/src_fedratinib.txt \
                    -replace_unk \
                    -output results/predictions_${model}_on_ChEMBL_test_best10.txt \
                    -batch_size 30 -max_length 500 -beam_size 10 -n_best 10 -gpu 0 
```

here is error message:

```
/home/anaconda3/envs/Macformer/lib/python3.6/site-packages/torchtext/data/field.py:359: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  var = torch.tensor(arr, dtype=self.dtype, device=device)
Traceback (most recent call last):
  File "translate.py", line 37, in <module>
    main(opt)
  File "translate.py", line 25, in main
    attn_debug=opt.attn_debug)
  File "/home/tools/Macformer/onmt/translate/translator.py", line 235, in translate
    batch_data = self.translate_batch(batch, data, fast=self.fast)
  File "/home/tools/Macformer/onmt/translate/translator.py", line 344, in translate_batch
    return self._translate_batch(batch, data)
  File "/home/tools/Macformer/onmt/translate/translator.py", line 604, in _translate_batch
    enc_states, memory_bank, src_lengths = self.model.encoder(src, src_lengths)
  File "/home/anaconda3/envs/Macformer/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tools/Macformer/onmt/encoders/transformer.py", line 112, in forward
    out = self.transformer[i](out, mask)
  File "/home/anaconda3/envs/Macformer/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tools/Macformer/onmt/encoders/transformer.py", line 50, in forward
    mask=mask)
  File "/home/anaconda3/envs/Macformer/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tools/Macformer/onmt/modules/multi_headed_attn.py", line 164, in forward
    key = self.linear_keys(key)
  File "/home/anaconda3/envs/Macformer/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/anaconda3/envs/Macformer/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/anaconda3/envs/Macformer/lib/python3.6/site-packages/torch/nn/functional.py", line 1372, in linear
    output = input.matmul(weight.t())
**RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)**
```

pytorch is correctly running in other pytorch python script and cuda is available:

Fri Jun 28 13:58:19 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.42.02              Driver Version: 555.42.02      CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3080        Off |   00000000:65:00.0 Off |                  N/A |
| 30%   28C    P8             16W /  320W |      30MiB /  10240MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      2226      G   /usr/lib/xorg/Xorg                             16MiB |
+-----------------------------------------------------------------------------------------+

thanks in advance.

zhou

**Comment by ningzhilin** [comment]
I also have the same error. I tried to change the cudatoolkit and torch version in anaconda virtual env, but not work.  :(
